# Generated by Django 3.2.5 on 2021-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.FloatField()),
                ('product_photo', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
