# Generated by Django 3.2.5 on 2021-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
